# https://supabase.com/docs/guides/local-development/cli/config
project_id = "world-cup-2026-cooper"

[api]
enabled = true

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = [
  "http://localhost:5173/**",
  "https://nfernie.github.io/World-Cup-2026---Cooper/**",
  "https://nfernie.github.io/World-Cup-2026---Cooper/auth/callback",
]

[auth.email]
enable_signup = true
enable_confirmations = false
