/** Map FIFA codes to ISO 3166-1 alpha-2 for flagcdn.com */
const FIFA_TO_ISO: Record<string, string> = {
  MEX: 'mx',
  RSA: 'za',
  KOR: 'kr',
  CZE: 'cz',
  CAN: 'ca',
  QAT: 'qa',
  SUI: 'ch',
  BIH: 'ba',
  BRA: 'br',
  MAR: 'ma',
  HAI: 'ht',
  SCO: 'gb-sct',
  USA: 'us',
  PAR: 'py',
  AUS: 'au',
  TUR: 'tr',
  GER: 'de',
  CUW: 'cw',
  CIV: 'ci',
  ECU: 'ec',
  NED: 'nl',
  JPN: 'jp',
  TUN: 'tn',
  SWE: 'se',
  BEL: 'be',
  EGY: 'eg',
  IRN: 'ir',
  NZL: 'nz',
  ESP: 'es',
  CPV: 'cv',
  KSA: 'sa',
  URU: 'uy',
  FRA: 'fr',
  SEN: 'sn',
  NOR: 'no',
  IRQ: 'iq',
  ARG: 'ar',
  ALG: 'dz',
  AUT: 'at',
  JOR: 'jo',
  POR: 'pt',
  ENG: 'gb-eng',
  CRO: 'hr',
  COL: 'co',
  UZB: 'uz',
  COD: 'cd',
  PAN: 'pa',
  GHA: 'gh',
}

export function getFlagUrl(fifaCode: string, width = 120): string {
  const iso = FIFA_TO_ISO[fifaCode.toUpperCase()] ?? fifaCode.toLowerCase().slice(0, 2)
  return `https://flagcdn.com/w${width}/${iso}.png`
}
