-- Placeholder 48-team seed for development (update fifa codes when draw is final)
insert into public.teams (fifa_code, name, group_letter) values
  ('MEX', 'Mexico', 'A'),
  ('RSA', 'South Africa', 'A'),
  ('KOR', 'Korea Republic', 'A'),
  ('UNK1', 'Group A Team 4', 'A'),
  ('CAN', 'Canada', 'B'),
  ('QAT', 'Qatar', 'B'),
  ('SUI', 'Switzerland', 'B'),
  ('UNK2', 'Group B Team 4', 'B'),
  ('BRA', 'Brazil', 'C'),
  ('MAR', 'Morocco', 'C'),
  ('HAI', 'Haiti', 'C'),
  ('SCO', 'Scotland', 'C'),
  ('USA', 'United States', 'D'),
  ('PAR', 'Paraguay', 'D'),
  ('AUS', 'Australia', 'D'),
  ('UNK3', 'Group D Team 4', 'D'),
  ('GER', 'Germany', 'E'),
  ('CUW', 'Curaçao', 'E'),
  ('CIV', 'Côte d''Ivoire', 'E'),
  ('ECU', 'Ecuador', 'E'),
  ('NED', 'Netherlands', 'F'),
  ('JPN', 'Japan', 'F'),
  ('TUN', 'Tunisia', 'F'),
  ('UNK4', 'Group F Team 4', 'F'),
  ('BEL', 'Belgium', 'G'),
  ('EGY', 'Egypt', 'G'),
  ('IRN', 'Iran', 'G'),
  ('NZL', 'New Zealand', 'G'),
  ('ESP', 'Spain', 'H'),
  ('CPV', 'Cabo Verde', 'H'),
  ('KSA', 'Saudi Arabia', 'H'),
  ('URU', 'Uruguay', 'H'),
  ('FRA', 'France', 'I'),
  ('SEN', 'Senegal', 'I'),
  ('NOR', 'Norway', 'I'),
  ('UNK5', 'Group I Team 4', 'I'),
  ('ARG', 'Argentina', 'J'),
  ('ALG', 'Algeria', 'J'),
  ('AUT', 'Austria', 'J'),
  ('JOR', 'Jordan', 'J'),
  ('POR', 'Portugal', 'K'),
  ('ENG', 'England', 'K'),
  ('CRO', 'Croatia', 'K'),
  ('UNK6', 'Group K Team 4', 'K'),
  ('COL', 'Colombia', 'L'),
  ('UZB', 'Uzbekistan', 'L'),
  ('UNK7', 'Group L Team 3', 'L'),
  ('UNK8', 'Group L Team 4', 'L')
on conflict (fifa_code) do nothing;
