-- 48 teams — FIFA World Cup 2026 draw (groups A–L)
insert into public.teams (fifa_code, name, group_letter) values
  ('MEX', 'Mexico', 'A'),
  ('RSA', 'South Africa', 'A'),
  ('KOR', 'Korea Republic', 'A'),
  ('CZE', 'Czechia', 'A'),
  ('CAN', 'Canada', 'B'),
  ('QAT', 'Qatar', 'B'),
  ('SUI', 'Switzerland', 'B'),
  ('BIH', 'Bosnia and Herzegovina', 'B'),
  ('BRA', 'Brazil', 'C'),
  ('MAR', 'Morocco', 'C'),
  ('HAI', 'Haiti', 'C'),
  ('SCO', 'Scotland', 'C'),
  ('USA', 'United States', 'D'),
  ('PAR', 'Paraguay', 'D'),
  ('AUS', 'Australia', 'D'),
  ('TUR', 'Türkiye', 'D'),
  ('GER', 'Germany', 'E'),
  ('CUW', 'Curaçao', 'E'),
  ('CIV', 'Côte d''Ivoire', 'E'),
  ('ECU', 'Ecuador', 'E'),
  ('NED', 'Netherlands', 'F'),
  ('JPN', 'Japan', 'F'),
  ('TUN', 'Tunisia', 'F'),
  ('SWE', 'Sweden', 'F'),
  ('BEL', 'Belgium', 'G'),
  ('EGY', 'Egypt', 'G'),
  ('IRN', 'Iran', 'G'),
  ('NZL', 'New Zealand', 'G'),
  ('ESP', 'Spain', 'H'),
  ('CPV', 'Cabo Verde', 'H'),
  ('KSA', 'Saudi Arabia', 'H'),
  ('URU', 'Uruguay', 'H'),
  ('FRA', 'France', 'I'),
  ('SEN', 'Senegal', 'I'),
  ('NOR', 'Norway', 'I'),
  ('IRQ', 'Iraq', 'I'),
  ('ARG', 'Argentina', 'J'),
  ('ALG', 'Algeria', 'J'),
  ('AUT', 'Austria', 'J'),
  ('JOR', 'Jordan', 'J'),
  ('POR', 'Portugal', 'K'),
  ('ENG', 'England', 'K'),
  ('CRO', 'Croatia', 'K'),
  ('COL', 'Colombia', 'K'),
  ('UZB', 'Uzbekistan', 'K'),
  ('COD', 'Congo DR', 'K'),
  ('PAN', 'Panama', 'L'),
  ('GHA', 'Ghana', 'L')
on conflict (fifa_code) do nothing;
