name: Deploy Database Migrations

on:
  push:
    branches:
      - main # Triggers the workflow every time you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Supabase Boot
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Push Database Migrations
        run: supabase db push --method direct
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          # Replace 'your-ref-id' with your actual Supabase project reference string
          SUPABASE_PROJECT_REF: fyiegingyipqtxaiopng
